"""add case attrs

Revision ID: 01a896b3a07a
Revises: dc720ceeb5e9
Create Date: 2025-06-19 14:48:38.973237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a896b3a07a'
down_revision: Union[str, None] = 'dc720ceeb5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caseattributes', sa.Column('side_panel', sa.String(), nullable=True))
    op.add_column('caseattributes', sa.Column('cabinet_type', sa.String(), nullable=True))
    op.add_column('caseattributes', sa.Column('color', sa.String(), nullable=True))
    op.add_column('caseattributes', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('caseattributes', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caseattributes', 'model')
    op.drop_column('caseattributes', 'brand')
    op.drop_column('caseattributes', 'color')
    op.drop_column('caseattributes', 'cabinet_type')
    op.drop_column('caseattributes', 'side_panel')
    # ### end Alembic commands ###
