"""add memory attrs

Revision ID: 175c29739292
Revises: e04de3a8901c
Create Date: 2025-06-19 13:30:31.609219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175c29739292'
down_revision: Union[str, None] = 'e04de3a8901c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storageattributes', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('storageattributes', sa.Column('model', sa.String(), nullable=True))
    op.add_column('storageattributes', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('storageattributes', sa.Column('mem_type', sa.String(), nullable=True))
    op.add_column('storageattributes', sa.Column('interface', sa.String(), nullable=True))
    op.add_column('storageattributes', sa.Column('cache_mem', sa.Integer(), nullable=True))
    op.add_column('storageattributes', sa.Column('form_factor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storageattributes', 'form_factor')
    op.drop_column('storageattributes', 'cache_mem')
    op.drop_column('storageattributes', 'interface')
    op.drop_column('storageattributes', 'mem_type')
    op.drop_column('storageattributes', 'capacity')
    op.drop_column('storageattributes', 'model')
    op.drop_column('storageattributes', 'brand')
    # ### end Alembic commands ###
