"""create cpu cooler attrs table

Revision ID: 19163d965235
Revises: 286c0777fd4a
Create Date: 2025-06-18 18:26:08.425886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19163d965235'
down_revision: Union[str, None] = '286c0777fd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caseattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_caseattributes_id'), 'caseattributes', ['id'], unique=False)
    op.create_table('cpucoolerattributes',
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('fan_rpm_base', sa.Integer(), nullable=True),
    sa.Column('fan_rpm_max', sa.Integer(), nullable=True),
    sa.Column('noise_level_base', sa.Float(), nullable=True),
    sa.Column('noise_level_max', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_cpucoolerattributes_id'), 'cpucoolerattributes', ['id'], unique=False)
    op.create_table('gpuattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_gpuattributes_id'), 'gpuattributes', ['id'], unique=False)
    op.create_table('motherboardattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_motherboardattributes_id'), 'motherboardattributes', ['id'], unique=False)
    op.create_table('powersupplyattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_powersupplyattributes_id'), 'powersupplyattributes', ['id'], unique=False)
    op.create_table('ramattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_ramattributes_id'), 'ramattributes', ['id'], unique=False)
    op.create_table('storageattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_storageattributes_id'), 'storageattributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storageattributes_id'), table_name='storageattributes')
    op.drop_table('storageattributes')
    op.drop_index(op.f('ix_ramattributes_id'), table_name='ramattributes')
    op.drop_table('ramattributes')
    op.drop_index(op.f('ix_powersupplyattributes_id'), table_name='powersupplyattributes')
    op.drop_table('powersupplyattributes')
    op.drop_index(op.f('ix_motherboardattributes_id'), table_name='motherboardattributes')
    op.drop_table('motherboardattributes')
    op.drop_index(op.f('ix_gpuattributes_id'), table_name='gpuattributes')
    op.drop_table('gpuattributes')
    op.drop_index(op.f('ix_cpucoolerattributes_id'), table_name='cpucoolerattributes')
    op.drop_table('cpucoolerattributes')
    op.drop_index(op.f('ix_caseattributes_id'), table_name='caseattributes')
    op.drop_table('caseattributes')
    # ### end Alembic commands ###
