"""empty message

Revision ID: 249698674045
Revises: 01a896b3a07a
Create Date: 2025-06-19 15:37:30.289940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249698674045'
down_revision: Union[str, None] = '01a896b3a07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE cpuattributes
        SET base_speed = NULL
        WHERE base_speed IS NOT NULL AND base_speed !~ '^[0-9]+(\.[0-9]+)?$';
    """)
    op.execute("""
        UPDATE cpuattributes
        SET turbo_speed = NULL
        WHERE turbo_speed IS NOT NULL AND turbo_speed !~ '^[0-9]+(\.[0-9]+)?$';
    """)
    op.execute("""
        ALTER TABLE cpuattributes
        ALTER COLUMN base_speed TYPE DOUBLE PRECISION USING base_speed::double precision;
    """)
    op.execute("""
        ALTER TABLE cpuattributes
        ALTER COLUMN turbo_speed TYPE DOUBLE PRECISION USING turbo_speed::double precision;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cpuattributes', 'turbo_speed',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('cpuattributes', 'base_speed',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
