"""created cpu attrs table

Revision ID: 286c0777fd4a
Revises: f041cd0eb954
Create Date: 2025-06-18 13:48:29.564092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286c0777fd4a'
down_revision: Union[str, None] = 'f041cd0eb954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpuattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('socket_type', sa.String(), nullable=True),
    sa.Column('base_speed', sa.String(), nullable=True),
    sa.Column('turbo_speed', sa.String(), nullable=True),
    sa.Column('architechture', sa.String(), nullable=True),
    sa.Column('core_family', sa.String(), nullable=True),
    sa.Column('integrated_graphics', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=True),
    sa.Column('memory_speed', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('generation', sa.String(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_cpuattributes_id'), 'cpuattributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpuattributes_id'), table_name='cpuattributes')
    op.drop_table('cpuattributes')
    # ### end Alembic commands ###
