"""add power supply attrs

Revision ID: dc720ceeb5e9
Revises: ccee30af92ec
Create Date: 2025-06-19 14:40:47.604965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc720ceeb5e9'
down_revision: Union[str, None] = 'ccee30af92ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('powersupplyattributes', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('powersupplyattributes', sa.Column('model', sa.String(), nullable=True))
    op.add_column('powersupplyattributes', sa.Column('power', sa.Integer(), nullable=True))
    op.add_column('powersupplyattributes', sa.Column('efficiency', sa.String(), nullable=True))
    op.add_column('powersupplyattributes', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('powersupplyattributes', 'color')
    op.drop_column('powersupplyattributes', 'efficiency')
    op.drop_column('powersupplyattributes', 'power')
    op.drop_column('powersupplyattributes', 'model')
    op.drop_column('powersupplyattributes', 'brand')
    # ### end Alembic commands ###
