"""add ram attrs

Revision ID: e04de3a8901c
Revises: e61c1da9d7e5
Create Date: 2025-06-19 10:05:48.031874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04de3a8901c'
down_revision: Union[str, None] = 'e61c1da9d7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ramattributes', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('ramattributes', sa.Column('model', sa.String(), nullable=True))
    op.add_column('ramattributes', sa.Column('total_memory', sa.Integer(), nullable=True))
    op.add_column('ramattributes', sa.Column('one_unit_memory', sa.Integer(), nullable=True))
    op.add_column('ramattributes', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('ramattributes', sa.Column('ram_type', sa.String(), nullable=True))
    op.add_column('ramattributes', sa.Column('ram_speed', sa.Integer(), nullable=True))
    op.add_column('ramattributes', sa.Column('cas_latency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ramattributes', 'cas_latency')
    op.drop_column('ramattributes', 'ram_speed')
    op.drop_column('ramattributes', 'ram_type')
    op.drop_column('ramattributes', 'quantity')
    op.drop_column('ramattributes', 'one_unit_memory')
    op.drop_column('ramattributes', 'total_memory')
    op.drop_column('ramattributes', 'model')
    op.drop_column('ramattributes', 'brand')
    # ### end Alembic commands ###
