"""add motherboard attrs table

Revision ID: e61c1da9d7e5
Revises: 19163d965235
Create Date: 2025-06-19 09:37:21.124245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61c1da9d7e5'
down_revision: Union[str, None] = '19163d965235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motherboardattributes', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('motherboardattributes', sa.Column('model', sa.String(), nullable=True))
    op.add_column('motherboardattributes', sa.Column('chipset', sa.String(), nullable=True))
    op.add_column('motherboardattributes', sa.Column('form_factor', sa.String(), nullable=True))
    op.add_column('motherboardattributes', sa.Column('socket_type', sa.String(), nullable=True))
    op.add_column('motherboardattributes', sa.Column('ram_slots', sa.Integer(), nullable=True))
    op.add_column('motherboardattributes', sa.Column('max_ram_support', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motherboardattributes', 'max_ram_support')
    op.drop_column('motherboardattributes', 'ram_slots')
    op.drop_column('motherboardattributes', 'socket_type')
    op.drop_column('motherboardattributes', 'form_factor')
    op.drop_column('motherboardattributes', 'chipset')
    op.drop_column('motherboardattributes', 'model')
    op.drop_column('motherboardattributes', 'brand')
    # ### end Alembic commands ###
