"""add gpu attrs

Revision ID: fdf95c8b5c55
Revises: 175c29739292
Create Date: 2025-06-19 14:18:32.327657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf95c8b5c55'
down_revision: Union[str, None] = '175c29739292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpuattributes', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('gpuattributes', sa.Column('model', sa.String(), nullable=True))
    op.add_column('gpuattributes', sa.Column('memory', sa.Integer(), nullable=True))
    op.add_column('gpuattributes', sa.Column('mem_interface', sa.String(), nullable=True))
    op.add_column('gpuattributes', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('gpuattributes', sa.Column('interface', sa.String(), nullable=True))
    op.add_column('gpuattributes', sa.Column('chipset', sa.String(), nullable=True))
    op.add_column('gpuattributes', sa.Column('base_clock', sa.Integer(), nullable=True))
    op.add_column('gpuattributes', sa.Column('clock_speed', sa.Integer(), nullable=True))
    op.add_column('gpuattributes', sa.Column('frame_sync', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpuattributes', 'frame_sync')
    op.drop_column('gpuattributes', 'clock_speed')
    op.drop_column('gpuattributes', 'base_clock')
    op.drop_column('gpuattributes', 'chipset')
    op.drop_column('gpuattributes', 'interface')
    op.drop_column('gpuattributes', 'length')
    op.drop_column('gpuattributes', 'mem_interface')
    op.drop_column('gpuattributes', 'memory')
    op.drop_column('gpuattributes', 'model')
    op.drop_column('gpuattributes', 'brand')
    # ### end Alembic commands ###
